name: React Build Deployment

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 关键修改：所有操作切换到/react目录
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          react/node_modules     # 修改缓存路径
          **/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('react/package-lock.json') }}  # 路径修改

    # 在子目录中执行命令
    - name: Install dependencies
      working-directory: ./react  # 指定工作目录
      run: npm ci

    - name: Build project
      working-directory: ./react  # 指定工作目录
      run: npm run build 

    # - name: Create docker directory
    #   run: mkdir -p docker/build
      
    - name: Move build files to docker directory
      run: mv ./react/build ./docker

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build docker
      working-directory: ./docker
      run: |
        docker build -t miku_music_card:latest .
        docker save -o miku_music_card.tar miku_music_card:latest
      env:
        DOCKER_BUILDKIT: 1

    - name: Archive Docker image
      uses: actions/upload-artifact@v4
      with:
        name: miku_music_card_docker_image
        path: docker/miku_music_card.tar
