name: React CI

on:
  push:
    branches: [ "main", "dev" ]  # 触发分支
  pull_request:
    branches: [ "main" ]         # PR 触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x      # 指定 Node 版本
          cache: 'npm'            # 自动缓存依赖

      # 步骤 3: 安装依赖
      - name: Install dependencies
        run: npm ci              # 推荐用 ci 代替 install

      # 步骤 4: 构建项目
      - name: Build
        run: npm run build
        env:
          CI: true                # 强制启用 CI 模式

      # 步骤 5: 上传构建产物（可选）
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: build/            # 上传构建目录
